language: node_js
  - "node"
services:
  - docker
  - mongodb

env:
  - ENVIRONMENT=TESTING

before_install:
  - docker-compose -f docker-compose.ci_test.yml build

script:
  - bash -c "./wait-for-it.sh localhost:27017 && npm test"
