language: node_js
  - "node"

services:
  - docker
  - mongodb

env:
  - ENVIRONMENT=TESTING

before_install:
  - docker-compose -f docker-compose.ci_test.yml build

script:
  - docker-compose -f docker-compose.ci_test.yml up
