language: node_js
node_js:
  - node
services:
  - docker
  - mongodb
before_install:
  - docker-compose -f docker-compose.ci_test.yml build
script:
  - docker-compose -f docker-compose.ci_test.yml up
  - npm install -g serverless
  - serverless deploy
env:
  - MONGO_URI=${MONGO_URI}
