language: node_js
node_js:
- node
services:
- docker
- mongodb
before_install:
- docker-compose -f docker-compose.ci_test.yml build
script:
- docker-compose -f docker-compose.ci_test.yml up
- npm install -g serverless
- serverless deploy
env:
- MONGO_URI=${MONGO_URI}
deploy:
  secret_access_key:
    secure: rDYZwF6cbmKbrdszted4L2QCSaFq+pb9YWJtEdd0JyRQKYxLIJcV5Hh6/wu3IqSMLEjHGP8QBvIW7U8QThwxh7RDLHvnfCC+h890bWU0dWT4XJ1vABQ5CMLjMxxAXGjKuk4j/LVeEIRdrDEISWK9h53Cn5LP4Vk6nOQ7C5/s+zbfvx5SC5vcdQxVeTnvvalmjkanp729nSDr2cUYyqG0wfGp0GuIi+JKCB2CpU6bYlqQj8F1JbQO6n48OOa1uoUjxeAzA+sCJofTArbxdd2lgH1lgkXPEKxg3i5MJjfzfXOApl/uj6WkEfGrzhRKfm1h0+G3sjxBV7HV/RpXm8EFLvuxOwQFzDawhe55mu7nyPdDBnXKZdLOy4BAy+vMDG0UPyYNbqtseBkw8gOrmPKpbKFLXyuLUpUlzWFdkS736DMmwTzzV1sfIiH8Yhp7dU6vEMyc4x+g9jgIHCxGNijWo1Govx7gcYFc0MZiiJ7T1emY6m0/hf5j8h7qJyaibnGfC362B9FukiTdK/YXnktzVBg5W6el9p2DEDW2SpdIDA19rUiKUcHr45tUXiLmmDSM6pfd95/XfWfCIZFKdSCbcLLj/6EGu59dzjGjWwctD9maI8gu0t/7DZGVnXNP9HVg1TT8rcMJhuTdumY1CgV8weNd5Y1LgEwpw9rFGNEhn4g=
