language: node_js
  - "node"

services:
  - docker
  - mongodb

before_install:
  - docker-compose -f docker-compose.ci_test.yml build

script:
  - docker-compose -f docker-compose.ci_test.yml up

deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs4.3"
  handler_name: "handler"