# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  environment:
    MONGO_URI: "mongodb+srv://billchee:wmi123456@cs3219.dq8sd.mongodb.net/mydb?retryWrites=true&w=majority"

functions:
  app:
    handler: src/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'